{{- if or .Values.metadataStore.enabled (eq (include "castai-agent.provider" .) "anywhere") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.metadataStore.configMapName }}
  namespace: {{ default .Release.Namespace .Values.metadataStore.configMapNamespace }}
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  {{- if gt (len .Values.commonAnnotations) 0 }}
  annotations:
    {{- include "castai-agent.annotations" . | nindent 4 }}
  {{- end }}
data:
  API_URL: {{ required "apiURL must be provided" (coalesce (dig "castai" "apiURL" "" (.Values.global | default dict)) .Values.apiURL) | quote }}
  GRPC_URL: {{ required "grpcURL must be provided" (coalesce (dig "castai" "grpcURL" "" (.Values.global | default dict)) .Values.grpcURL) | quote }}
  # CLUSTER_ID is populated at runtime by the agent after it registers with the CAST AI backend.
  CLUSTER_ID: ""
{{- end }}
