# Default values for castai-dbo umbrella chart.

# -- Global values forwarded to all sub-charts.
global:
  # -- Organization ID shared by all DBO components.
  organizationID: ""

db-proxy:
  enabled: true

db-agent:
  enabled: true

db-optimizer:
  enabled: true
