apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "castai-db-proxy.name" . }}-config
  labels:
    {{- include "castai-db-proxy.labels" . | nindent 4 }}
  annotations:
    {{- include "castai-db-proxy.annotations" . | nindent 4 }}
data:
  config.toml: |
    protocol = {{ .Values.protocol | quote }}
    rw_listen_port = {{ .Values.ports.readWrite }}
    ro_listen_port = {{ .Values.ports.readOnly }}
    metrics_port = {{ .Values.ports.metrics }}

    {{- if not .Values.endpoints }}{{ fail "endpoints must contain at least one endpoint" }}{{ end }}
    {{- range .Values.endpoints }}
    [[fallback_endpoints]]
    address = {{ .address | quote }}
    readonly = {{ .readonly }}
    {{- end }}

    [api]
    url = {{ printf "https://%s" (required "apiURL must be provided" .Values.apiURL) | quote }}
    organization_id = {{ required "organizationID must be provided" .Values.organizationID | quote }}
    proxy_id = {{ required "proxyID must be provided" .Values.proxyID | quote }}

    [cache]
    default_ttl_secs = {{ .Values.cache.defaultTTLSecs }}
    {{- if .Values.cluster.enabled }}

    [cluster]
    listen_port = {{ .Values.ports.cluster }}

    [cluster.discovery]
    type = "dns"
    host = "headless-{{ include "castai-db-proxy.name" . }}.{{ .Release.Namespace }}.svc.cluster.local"
    port = {{ .Values.ports.cluster }}
    {{- end }}

    [server]
    grace_period_seconds = {{ .Values.connection_draining.grace_period_seconds }}
    graceful_shutdown_timeout_seconds = {{ .Values.connection_draining.graceful_shutdown_timeout_seconds }}
