apiVersion: v1
kind: Service
metadata:
  name: headless-{{ include "castai-db-proxy.name" . }}
  labels:
    {{- include "castai-db-proxy.labels" . | nindent 4 }}
  annotations:
    {{- include "castai-db-proxy.annotations" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: cluster
      port: {{ .Values.ports.cluster }}
      targetPort: cluster
      protocol: TCP
  selector:
    {{- include "castai-db-proxy.selectorLabels" . | nindent 4 }}
