{{- if and .Values.pooling.enabled .Values.pooling.proxySql .Values.pooling.proxySql.enabled }}
{{- $defaults := dict
  "threads" 4
  "max_connections" 2048
  "stacksize" 1048576
  "have_compress" true
  "free_connections_pct" 5
  "connect_timeout_server" 5000
  "default_query_timeout" 36000000
  "auto_increment_delay_multiplex" 5
  "max_backend_connections" 100
  "multiplexing" true
-}}
{{- $userConfig := .Values.pooling.proxySql.config | default dict -}}
{{- $mergedConfig := merge (deepCopy $userConfig) $defaults -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "castai-db-proxy.name" . }}-proxysql-config
  labels:
    {{- include "castai-db-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: pooling
  annotations:
    {{- include "castai-db-proxy.annotations" . | nindent 4 }}
data:
  proxysql.cnf: |
    datadir="/var/lib/proxysql"

    admin_variables=
    {
        admin_credentials="admin:admin"
        mysql_ifaces="127.0.0.1:6032"
        restapi_enabled=true
        restapi_port={{ .Values.pooling.metricsPort }}
    }

    mysql_variables=
    {
        threads={{ $mergedConfig.threads | int64 }}
        max_connections={{ $mergedConfig.max_connections | int64 }}
        stacksize={{ $mergedConfig.stacksize | int64 }}
        have_compress={{ $mergedConfig.have_compress }}
        free_connections_pct={{ $mergedConfig.free_connections_pct | int64 }}
        interfaces="0.0.0.0:{{ .Values.pooling.port }}"
        default_query_timeout={{ $mergedConfig.default_query_timeout | int64 }}
        connect_timeout_server={{ $mergedConfig.connect_timeout_server | int64 }}
        auto_increment_delay_multiplex={{ $mergedConfig.auto_increment_delay_multiplex | int64 }}
        monitor_enabled=false
        have_ssl=true
        ssl_cert="/etc/proxysql/proxysql.crt"
        ssl_key="/etc/proxysql/proxysql.key"
    }

    mysql_servers=
    (
    {{- range $index, $endpoint := .Values.endpoints }}
      {
        address="{{ required "endpoint address must be provided" $endpoint.address | splitList ":" | first }}"
        port={{ required "endpoint address must contain host:port" $endpoint.address | splitList ":" | last | int64 }}
        hostgroup={{ ternary 1 0 .readonly }}
        max_connections={{ $mergedConfig.max_backend_connections | int64 }}
        use_ssl=1
      }{{ if lt $index (sub (len $.Values.endpoints) 1) }},{{ end }}
    {{- end }}
    )

    mysql_query_rules=
    (
    {{- range $index, $endpoint := .Values.endpoints }}
      {
        rule_id={{ add $index 1 }}
        active=1
        destination_hostgroup={{ ternary 1 0 .readonly }}
        apply=1
        multiplex={{ if $mergedConfig.multiplexing }}2{{ else }}0{{ end }}
      }{{ if lt $index (sub (len $.Values.endpoints) 1) }},{{ end }}
    {{- end }}
    )
{{- end }}
