{{- if and .Values.pooling.enabled .Values.pooling.proxySql .Values.pooling.proxySql.enabled (not .Values.pooling.proxySql.usersSecretRef) }}
{{- if or .Values.pooling.proxySql.user .Values.pooling.proxySql.users }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "castai-db-proxy.name" . }}-proxysql-users
  labels:
    {{- include "castai-db-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: pooling
  annotations:
    {{- include "castai-db-proxy.annotations" . | nindent 4 }}
type: Opaque
stringData:
  users.toml: |
    {{- range .Values.pooling.proxySql.users }}
    [[users]]
    username = {{ .username | quote }}
    password = {{ .password | quote }}
    {{- end }}
    {{- if and (not .Values.pooling.proxySql.users) .Values.pooling.proxySql.user }}
    [[users]]
    username = {{ .Values.pooling.proxySql.user | quote }}
    password = {{ .Values.pooling.proxySql.password | quote }}
    {{- end }}
{{- end }}
{{- end }}
