{{- if and .Values.pooling.enabled .Values.pooling.proxySql .Values.pooling.proxySql.enabled }}
{{- if and .Values.pooling.proxySql.users (not .Values.pooling.proxySql.usersSecretRef) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "castai-db-proxy.name" . }}-proxysql-users
  labels:
    {{- include "castai-db-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: pooling
  annotations:
    {{- include "castai-db-proxy.annotations" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.pooling.proxySql.usersSecretKey | quote }}: |
    {{- range .Values.pooling.proxySql.users }}
    {{ .username }}:{{ .password }}
    {{- end }}
{{- end }}
{{- end }}
