apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
spec:
  {{- with .Values.service.trafficDistribution }}
  trafficDistribution: {{ . }}
  {{- end }}
  ports:
    - name: rw
      port: {{ .Values.ports.readWrite }}
      targetPort: rw
      protocol: TCP
    - name: ro
      port: {{ .Values.ports.readonly }}
      targetPort: ro
      protocol: TCP
    - name: metrics
      port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
