{{- with .Values.model.hfToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sglang.hfSecretName" $ }}
  labels:
    {{- include "sglang.labels" $ | nindent 4 }}
type: Opaque
data:
  hfToken: {{ . | b64enc | quote }}
{{- end }}
