{{- if or .Values.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "castai-db-agent.name" . }}-api-key
  labels:
    {{- include "castai-db-agent.labels" . | nindent 4 }}
data:
  API_KEY: {{ .Values.apiKey | b64enc | quote }}
{{- end }}
