apiVersion: v1
kind: Service
metadata:
  name: headless-{{ include "castai-db-optimizer.name" . }}
  labels:
    {{- include "castai-db-optimizer.labels" . | nindent 4 }}
  annotations:
    {{- include "castai-db-optimizer.annotations" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 9050
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "castai-db-optimizer.selectorLabels" . | nindent 4 }}
