apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "castai-db-optimizer.name" . }}
  labels:
    {{- include "castai-db-optimizer.labels" . | nindent 4 }}
  annotations:
    {{- include "castai-db-optimizer.annotations" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "castai-db-optimizer.selectorLabels" . | nindent 6 }}
