{{- if and .Values.proxySql .Values.proxySql.enabled .Values.proxySql.user .Values.proxySql.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}-proxysql-users
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
type: Opaque
stringData:
  PROXY_SQL_USERNAME: {{ .Values.proxySql.user | quote }}
  PROXY_SQL_PASSWORD: {{ .Values.proxySql.password | quote }}
  PROXY_SQL_ADMIN_USERNAME: {{ .Values.proxySql.adminUser | default "admin" | quote }}
  PROXY_SQL_ADMIN_PASSWORD: {{ .Values.proxySql.adminPassword | default "admin" | quote }}
{{- end }}
