{{- if and .Values.proxySql .Values.proxySql.enabled (not .Values.proxySql.usersSecretRef) }}
{{- if or .Values.proxySql.user .Values.proxySql.users }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}-proxysql-users
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
type: Opaque
stringData:
  users.json: |
    {{- if .Values.proxySql.users }}
    {{ .Values.proxySql.users | toJson }}
    {{- else }}
    [{"username":{{ .Values.proxySql.user | quote }},"password":{{ .Values.proxySql.password | quote }}}]
    {{- end }}
{{- end }}
{{- end }}
