{{- if .Values.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "castai-db-optimizer.name" . }}
  labels:
    {{- include "castai-db-optimizer.labels" . | nindent 4 }}
  annotations:
    {{- include "castai-db-optimizer.annotations" . | nindent 4 }}
data:
  API_KEY: {{ .Values.apiKey | b64enc | quote }}
{{- end }}
