apiVersion: v2
name: autoscaler-anywhere
description: Wrapper chart for CAST AI Autoscaler Anywhere profile (non-managed clusters).
type: application
version: 0.4.0
dependencies:
  - name: castai-agent
    version: "0.149.0"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-agent.enabled
  - name: castai-cluster-controller
    version: "0.91.0"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-cluster-controller.enabled
  - name: castai-workload-autoscaler
    version: "0.1.191"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-workload-autoscaler.enabled
  - name: castai-workload-autoscaler-exporter
    version: "0.0.110"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-workload-autoscaler-exporter.enabled
  - name: castai-evictor
    version: "0.35.6"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-evictor.enabled
  - name: castai-pod-mutator
    version: "0.7.0"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-pod-mutator.enabled
