apiVersion: v2
name: autoscaler-openshift
description: Wrapper chart for CAST AI Autoscaler OpenShift profile.
type: application
version: 0.1.0
dependencies:
  - name: castai-agent
    version: "0.151.0"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-agent.enabled
