castai-agent:
  enabled: true
  replicaCount: 1
  apiKeySecretRef: castai-credentials
  createNamespace: false

castai-spot-handler:
  enabled: true
  castai:
    provider: ""
    clusterIdConfigMapKeyRef:
      name: castai-agent-metadata
      key: CLUSTER_ID
  apiKeySecretRef: castai-credentials

castai-kvisor:
  enabled: true
  castai:
    apiKeySecretRef: castai-credentials
    clusterIdConfigMapKeyRef:
      name: castai-agent-metadata
      key: CLUSTER_ID

gpu-metrics-exporter:
  enabled: true
  castai:
    apiKeySecretRef: castai-credentials
    clusterIdConfigMapKeyRef:
      name: castai-agent-metadata
      key: CLUSTER_ID
