{{- if .Values.castai.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "castai-kentroller.fullname" . }}
  labels:
    {{- include "castai-kentroller.labels" . | nindent 4 }}
data:
  API_KEY: {{ required "castai.apiKey must be provided" .Values.castai.apiKey | b64enc | quote }}
{{- end }}
