apiVersion: v2
name: kent
description: Wrapper chart for CAST AI Kent profile.
type: application
version: 0.9.0
dependencies:
  - name: castai-agent
    version: "0.151.0"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-agent.enabled
  - name: castai-cluster-controller
    version: "0.91.1"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-cluster-controller.enabled
  - name: castai-kentroller
    version: "0.1.110"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-kentroller.enabled
  - name: castai-workload-autoscaler
    version: "0.1.200"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-workload-autoscaler.enabled
  - name: castai-live
    version: "0.82.0"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-live.enabled
  - name: castai-pod-mutator
    version: "0.7.0"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-pod-mutator.enabled
  - name: castai-evictor
    version: "0.35.15"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-evictor.enabled
  - name: metrics-server
    version: "3.13.0"
    repository: "https://kubernetes-sigs.github.io/metrics-server/"
    condition: metrics-server.enabled
