{{- $crd := .Files.Get "files/recommendations.yaml" -}}
{{- if .Values.crds.keep -}}
{{- $crd = replace "  annotations:\n" "  annotations:\n    helm.sh/resource-policy: keep\n" $crd -}}
{{- end -}}
{{ $crd }}
