apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.430
appVersion: 85f9a4125c13b5173d741491081d29e35cf8b987
annotations:
  release-date: "2026-04-02T14:02:47"
