apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.434
appVersion: dd3974f3e53913828b464f28bd5d68f8ddf15a9e
annotations:
  release-date: "2026-04-03T08:26:41"
