apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.427
appVersion: 269ee94410dda2c83d875f2fb24ae1910fa24895
annotations:
  release-date: "2026-04-02T09:01:55"
