apiVersion: v2
name: autoscaler
description: Wrapper chart for CAST AI Autoscaler profile.
type: application
version: 0.10.0
dependencies:
  - name: castai-agent
    version: "0.145.0"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-agent.enabled
  - name: castai-spot-handler
    version: "0.32.0"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-spot-handler.enabled
  - name: castai-cluster-controller
    version: "0.90.1"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-cluster-controller.enabled
  - name: castai-workload-autoscaler
    version: "0.1.186"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-workload-autoscaler.enabled
  - name: castai-workload-autoscaler-exporter
    version: "0.0.107"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-workload-autoscaler-exporter.enabled
  - name: castai-evictor
    version: "0.34.6"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-evictor.enabled
  - name: castai-pod-mutator
    version: "0.6.0"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-pod-mutator.enabled
  - name: castai-pod-pinner
    version: "1.10.0"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-pod-pinner.enabled
  - name: castai-ai-optimizer-proxy
    version: "0.0.115"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-ai-optimizer-proxy.enabled
  - name: castai-kvisor
    version: "1.0.131"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-kvisor.enabled
  - name: castai-live
    version: "0.75.1"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-live.enabled
  - name: gpu-metrics-exporter
    version: "0.1.29"
    repository: "https://castai.github.io/helm-charts"
    condition: gpu-metrics-exporter.enabled
