apiVersion: v2
name: autoscaler
description: CAST AI autoscaler mode — cluster-controller, evictor, pod-mutator, pod-pinner, castai-live.
type: application
version: 0.11.0
dependencies:
  - name: castai-cluster-controller
    version: "0.90.1"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-cluster-controller.enabled

  - name: castai-evictor
    version: "0.35.1"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-evictor.enabled

  - name: castai-pod-mutator
    version: "0.6.0"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-pod-mutator.enabled

  - name: castai-pod-pinner
    version: "1.10.0"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-pod-pinner.enabled

  - name: castai-live
    version: "0.75.1"
    repository: "https://castai.github.io/helm-charts"
    condition: castai-live.enabled
