{{- if .Values.crdUpgrade.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "exporter.fullname" . }}-crd-wait
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "exporter.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "exporter.fullname" . }}-crd-wait
  labels:
    {{- include "exporter.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "exporter.fullname" . }}-crd-wait
  labels:
    {{- include "exporter.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "exporter.fullname" . }}-crd-wait
subjects:
- kind: ServiceAccount
  name: {{ include "exporter.fullname" . }}-crd-wait
  namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "exporter.fullname" . }}-crd-wait-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "exporter.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 300
  template:
    metadata:
      name: {{ include "exporter.fullname" . }}-crd-wait
      labels:
        {{- include "exporter.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "exporter.fullname" . }}-crd-wait
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: wait-crd
        image: {{ include "exporter.imageRepository" (list .Values.crdUpgrade.image.repository .) }}:{{ .Values.crdUpgrade.image.tag }}
        imagePullPolicy: IfNotPresent
        args:
        - wait
        - --for=condition=Established
        - crd/custommetricsexporterconfigs.autoscaling.cast.ai
        - --timeout=60s
        {{- with .Values.crdUpgrade.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
