{{- if .Values.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exporter.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.prometheus.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "exporter.fullname" . }}-prometheus
      app.kubernetes.io/name: {{ include "exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "exporter.fullname" . }}-prometheus
        app.kubernetes.io/name: {{ include "exporter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/prometheus-config.yaml") . | sha256sum }}
        workloads.cast.ai/configuration: |
          vertical:
            optimization: "on"
          scalingPolicyName: balanced
    spec:
      {{- if .Values.priorityClass.enabled }}
      priorityClassName: {{ .Values.priorityClass.name }}
      {{- end }}
      serviceAccountName: {{ template "exporter.serviceAccountName" . }}-prometheus
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prometheus.podSecurityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: prometheus
          image: "{{ include "exporter.prometheus.imageRepository" . }}:{{ .Values.prometheus.image.tag }}"
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.retention.time={{ .Values.prometheus.storage.retention }}"
            - "--storage.tsdb.path=/prometheus/data"
          ports:
            - containerPort: 9090
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
          {{- with .Values.prometheus.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: prometheus-data
              mountPath: /prometheus/data
          readinessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "exporter.fullname" . }}-prometheus-config
        - name: prometheus-data
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with include "exporter.tolerations" . }}
      tolerations:
      {{- . | nindent 8 }}
      {{- end }}
{{- end }}
