apiVersion: v2
name: castai-workload-autoscaler-exporter
description: CAST AI workload autoscaler exporter.
type: application

# version & appVersion are set to a workload-autoscaler/{tagValue} (gitlab/remote-release-template.yml > chart_version_from_tag.py)
version: 1.0.7
appVersion: "v1.0.7"
